"""add applications table and new user roles

Revision ID: 195c1c3a7091
Revises: 06e25db3b6f2
Create Date: 2025-09-20 12:11:31.705549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195c1c3a7091'
down_revision: Union[str, None] = '06e25db3b6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create applications table
    op.create_table('applications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('financier_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=True),
        sa.Column('financier_approved_at', sa.DateTime(), nullable=True),
        sa.Column('financier_rejected_at', sa.DateTime(), nullable=True),
        sa.Column('financier_user_id', sa.Integer(), nullable=True),
        sa.Column('mvd_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=True),
        sa.Column('mvd_approved_at', sa.DateTime(), nullable=True),
        sa.Column('mvd_rejected_at', sa.DateTime(), nullable=True),
        sa.Column('mvd_user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['financier_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['mvd_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    
    # Add new enum values to userrole
    op.execute("ALTER TYPE userrole ADD VALUE 'financier'")
    op.execute("ALTER TYPE userrole ADD VALUE 'mvd'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove enum values (PostgreSQL doesn't support removing enum values directly)
    # We would need to recreate the enum, but that's complex and not needed for now
    
    # Drop applications table
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    
    # ### end Alembic commands ###
