"""empty message

Revision ID: 1bbd64872d39
Revises: 
Create Date: 2025-04-15 16:03:46.374629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbd64872d39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('iin', sa.String(length=12), nullable=True),
    sa.Column('drivers_license_expiry', sa.DateTime(), nullable=True),
    sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selfie_with_license_url', sa.String(), nullable=True),
    sa.Column('drivers_license_url', sa.String(), nullable=True),
    sa.Column('id_card_front_url', sa.String(), nullable=True),
    sa.Column('id_card_back_url', sa.String(), nullable=True),
    sa.Column('id_card_expiry', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'REJECTED', 'FIRST', 'PENDING', 'MECHANIC', name='userrole'), nullable=True),
    sa.Column('last_sms_code', sa.String(), nullable=True),
    sa.Column('sms_code_valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('gps_id', sa.String(), nullable=True),
    sa.Column('gps_imei', sa.String(), nullable=True),
    sa.Column('fuel_level', sa.Float(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('price_per_minute', sa.Integer(), nullable=False),
    sa.Column('price_per_hour', sa.Integer(), nullable=False),
    sa.Column('price_per_day', sa.Integer(), nullable=False),
    sa.Column('car_class', sa.Integer(), nullable=True),
    sa.Column('engine_volume', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('drive_type', sa.Integer(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('current_renter_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_renter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_table('rental_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('rental_type', sa.Enum('MINUTES', 'HOURS', 'DAYS', name='rentaltype'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('end_latitude', sa.Float(), nullable=True),
    sa.Column('end_longitude', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('reservation_time', sa.DateTime(), nullable=False),
    sa.Column('photos_before', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('photos_after', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('already_payed', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('rental_status', sa.Enum('RESERVED', 'IN_USE', 'COMPLETED', 'DELIVERING', 'CANCELLED', name='rentalstatus'), nullable=False),
    sa.Column('delivery_latitude', sa.Float(), nullable=True),
    sa.Column('delivery_longitude', sa.Float(), nullable=True),
    sa.Column('delivery_mechanic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['delivery_mechanic_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_history_id'), 'rental_history', ['id'], unique=False)
    op.create_table('rental_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rental_history.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rental_id')
    )
    op.create_index(op.f('ix_rental_reviews_id'), 'rental_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_reviews_id'), table_name='rental_reviews')
    op.drop_table('rental_reviews')
    op.drop_index(op.f('ix_rental_history_id'), table_name='rental_history')
    op.drop_table('rental_history')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
