"""empty message

Revision ID: 21541e0a5163
Revises: 749fd06cbfc2
Create Date: 2025-06-03 18:10:08.296784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21541e0a5163'
down_revision: Union[str, None] = '749fd06cbfc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('mileage', sa.Integer(), nullable=True))
    op.add_column('rental_history', sa.Column('delivery_photos_before', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('rental_history', sa.Column('delivery_photos_after', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_history', 'delivery_photos_after')
    op.drop_column('rental_history', 'delivery_photos_before')
    op.drop_column('cars', 'mileage')
    # ### end Alembic commands ###
