"""Add delivery time tracking fields

Revision ID: 3c445a622bb0
Revises: 9a47928fea56
Create Date: 2025-01-14 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c445a622bb0'
down_revision = '9a47928fea56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_history', sa.Column('delivery_start_time', sa.DateTime(), nullable=True))
    op.add_column('rental_history', sa.Column('delivery_end_time', sa.DateTime(), nullable=True))
    op.add_column('rental_history', sa.Column('delivery_penalty_fee', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_history', 'delivery_penalty_fee')
    op.drop_column('rental_history', 'delivery_end_time')
    op.drop_column('rental_history', 'delivery_start_time')
    # ### end Alembic commands ###
