"""empty message

Revision ID: 48090727e981
Revises: 7a94d3b021d6
Create Date: 2025-04-02 10:54:10.264963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48090727e981'
down_revision: Union[str, None] = '7a94d3b021d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_faces_id', table_name='faces')
    op.drop_index('ix_faces_name', table_name='faces')
    op.drop_table('faces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='faces_pkey')
    )
    op.create_index('ix_faces_name', 'faces', ['name'], unique=True)
    op.create_index('ix_faces_id', 'faces', ['id'], unique=False)
    # ### end Alembic commands ###
