"""empty message

Revision ID: 4e268ed9b18f
Revises: 0fffcb73e150
Create Date: 2025-04-03 15:34:24.610826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e268ed9b18f'
down_revision: Union[str, None] = '0fffcb73e150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('course', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'course')
    # ### end Alembic commands ###
