"""empty message

Revision ID: 5b6db3ed38b9
Revises: 21541e0a5163
Create Date: 2025-06-05 18:18:01.970220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6db3ed38b9'
down_revision: Union[str, None] = '21541e0a5163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_history', sa.Column('fuel_before', sa.Float(), nullable=True))
    op.add_column('rental_history', sa.Column('fuel_after', sa.Float(), nullable=True))
    op.add_column('rental_history', sa.Column('mileage_before', sa.Integer(), nullable=True))
    op.add_column('rental_history', sa.Column('mileage_after', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_history', 'mileage_after')
    op.drop_column('rental_history', 'mileage_before')
    op.drop_column('rental_history', 'fuel_after')
    op.drop_column('rental_history', 'fuel_before')
    # ### end Alembic commands ###
