"""empty message

Revision ID: 5eb85c66548b
Revises: fd4f4093bf78
Create Date: 2025-03-04 13:48:49.391047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb85c66548b'
down_revision: Union[str, None] = 'fd4f4093bf78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('embedding', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faces_id'), 'faces', ['id'], unique=False)
    op.create_index(op.f('ix_faces_name'), 'faces', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faces_name'), table_name='faces')
    op.drop_index(op.f('ix_faces_id'), table_name='faces')
    op.drop_table('faces')
    # ### end Alembic commands ###
