"""empty message

Revision ID: 749fd06cbfc2
Revises: 8ea4ec302f7a
Create Date: 2025-05-30 18:39:19.287280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749fd06cbfc2'
down_revision: Union[str, None] = '8ea4ec302f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_history', sa.Column('base_price', sa.Integer(), nullable=True))
    op.add_column('rental_history', sa.Column('open_fee', sa.Integer(), nullable=True))
    op.add_column('rental_history', sa.Column('delivery_fee', sa.Integer(), nullable=True))
    op.add_column('rental_history', sa.Column('waiting_fee', sa.Integer(), nullable=True))
    op.add_column('rental_history', sa.Column('overtime_fee', sa.Integer(), nullable=True))
    op.add_column('rental_history', sa.Column('distance_fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_history', 'distance_fee')
    op.drop_column('rental_history', 'overtime_fee')
    op.drop_column('rental_history', 'waiting_fee')
    op.drop_column('rental_history', 'delivery_fee')
    op.drop_column('rental_history', 'open_fee')
    op.drop_column('rental_history', 'base_price')
    # ### end Alembic commands ###
