"""empty message

Revision ID: 7a94d3b021d6
Revises: 5eb85c66548b
Create Date: 2025-04-02 10:51:09.848519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a94d3b021d6'
down_revision: Union[str, None] = '5eb85c66548b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('engine_volume', sa.Float(), nullable=True))
    op.add_column('cars', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('photos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'photos')
    op.drop_column('cars', 'year')
    op.drop_column('cars', 'engine_volume')
    # ### end Alembic commands ###
