"""empty message

Revision ID: 8ea4ec302f7a
Revises: 639a4f38b37f
Create Date: 2025-05-26 14:25:28.779764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea4ec302f7a'
down_revision: Union[str, None] = '639a4f38b37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('documents_verified', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'documents_verified')
    # ### end Alembic commands ###
