"""Add transmission_type to cars

Revision ID: add_transmission_type
Revises: 195c1c3a7091
Create Date: 2025-01-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_transmission_type'
down_revision: Union[str, None] = '195c1c3a7091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create transmission_type enum if it doesn't exist
    transmission_type_enum = sa.Enum('manual', 'automatic', 'cvt', 'semi_automatic', name='transmissiontype')
    transmission_type_enum.create(op.get_bind(), checkfirst=True)
    
    # Add transmission_type column to cars table if it doesn't exist
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('cars')]
    
    if 'transmission_type' not in columns:
        op.add_column('cars', sa.Column('transmission_type', transmission_type_enum, nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove transmission_type column
    op.drop_column('cars', 'transmission_type')
    
    # Drop transmission_type enum
    transmission_type_enum = sa.Enum('manual', 'automatic', 'cvt', 'semi_automatic', name='transmissiontype')
    transmission_type_enum.drop(op.get_bind())
    
    # ### end Alembic commands ###
