"""empty message

Revision ID: adee2ccaa818
Revises: fcdb43da2af0
Create Date: 2025-06-20 21:43:20.628656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adee2ccaa818'
down_revision: Union[str, None] = 'fcdb43da2af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('OPEN_VEHICLE', 'CLOSE_VEHICLE', 'GIVE_KEY', 'TAKE_KEY', name='actiontype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rental_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_actions_id'), 'rental_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_actions_id'), table_name='rental_actions')
    op.drop_table('rental_actions')
    # ### end Alembic commands ###
