"""empty message

Revision ID: ba05a1b4f336
Revises: adee2ccaa818
Create Date: 2025-06-21 01:48:33.536151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba05a1b4f336'
down_revision: Union[str, None] = 'adee2ccaa818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('selfie_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'selfie_url')
    # ### end Alembic commands ###
