"""empty message

Revision ID: babe89608602
Revises: 129df154b9f7
Create Date: 2025-04-06 11:28:11.558873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'babe89608602'
down_revision: Union[str, None] = '129df154b9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_history', sa.Column('reservation_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_history', 'reservation_time')
    # ### end Alembic commands ###
