"""empty message

Revision ID: c7364271d6a8
Revises: ee9361a82b19
Create Date: 2025-04-07 17:03:02.981449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7364271d6a8'
down_revision: Union[str, None] = 'ee9361a82b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rental_history.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rental_id')
    )
    op.create_index(op.f('ix_rental_reviews_id'), 'rental_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_reviews_id'), table_name='rental_reviews')
    op.drop_table('rental_reviews')
    # ### end Alembic commands ###
