"""empty message

Revision ID: ee9361a82b19
Revises: 42a119e5bb57
Create Date: 2025-04-07 11:37:56.150738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9361a82b19'
down_revision: Union[str, None] = '42a119e5bb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('car_class', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'car_class')
    # ### end Alembic commands ###
