"""remove_guarantor_first_name_last_name_columns

Revision ID: remove_guarantor_names
Revises: 9a47928fea56
Create Date: 2024-01-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_guarantor_names'
down_revision = '9a47928fea56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guarantor_requests', 'guarantor_last_name')
    op.drop_column('guarantor_requests', 'guarantor_first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guarantor_requests', sa.Column('guarantor_first_name', sa.VARCHAR(), nullable=True))
    op.add_column('guarantor_requests', sa.Column('guarantor_last_name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
