"""Split names into first_name and last_name

Revision ID: split_names_001
Revises: fcdb43da2af0
Create Date: 2024-01-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'split_names_001'
down_revision = 'fcdb43da2af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем новые колонки в таблицу users
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    
    # Добавляем новые колонки в таблицу guarantor_requests
    op.add_column('guarantor_requests', sa.Column('guarantor_first_name', sa.String(), nullable=True))
    op.add_column('guarantor_requests', sa.Column('guarantor_last_name', sa.String(), nullable=True))
    
    # Мигрируем данные из full_name в first_name и last_name
    # Для users таблицы
    op.execute("""
        UPDATE users 
        SET first_name = CASE 
            WHEN full_name IS NOT NULL AND position(' ' in full_name) > 0 
            THEN trim(substring(full_name from 1 for position(' ' in full_name) - 1))
            ELSE full_name
        END,
        last_name = CASE 
            WHEN full_name IS NOT NULL AND position(' ' in full_name) > 0 
            THEN trim(substring(full_name from position(' ' in full_name) + 1))
            ELSE NULL
        END
        WHERE full_name IS NOT NULL
    """)
    
    # Для guarantor_requests таблицы
    op.execute("""
        UPDATE guarantor_requests 
        SET guarantor_first_name = CASE 
            WHEN guarantor_name IS NOT NULL AND position(' ' in guarantor_name) > 0 
            THEN trim(substring(guarantor_name from 1 for position(' ' in guarantor_name) - 1))
            ELSE guarantor_name
        END,
        guarantor_last_name = CASE 
            WHEN guarantor_name IS NOT NULL AND position(' ' in guarantor_name) > 0 
            THEN trim(substring(guarantor_name from position(' ' in guarantor_name) + 1))
            ELSE NULL
        END
        WHERE guarantor_name IS NOT NULL
    """)
    
    # Удаляем старые колонки
    op.drop_column('users', 'full_name')
    op.drop_column('guarantor_requests', 'guarantor_name')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем обратно старые колонки
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('guarantor_requests', sa.Column('guarantor_name', sa.String(), nullable=True))
    
    # Мигрируем данные обратно из first_name и last_name в full_name
    # Для users таблицы
    op.execute("""
        UPDATE users 
        SET full_name = CASE 
            WHEN first_name IS NOT NULL AND last_name IS NOT NULL 
            THEN first_name || ' ' || last_name
            WHEN first_name IS NOT NULL 
            THEN first_name
            ELSE NULL
        END
        WHERE first_name IS NOT NULL OR last_name IS NOT NULL
    """)
    
    # Для guarantor_requests таблицы
    op.execute("""
        UPDATE guarantor_requests 
        SET guarantor_name = CASE 
            WHEN guarantor_first_name IS NOT NULL AND guarantor_last_name IS NOT NULL 
            THEN guarantor_first_name || ' ' || guarantor_last_name
            WHEN guarantor_first_name IS NOT NULL 
            THEN guarantor_first_name
            ELSE NULL
        END
        WHERE guarantor_first_name IS NOT NULL OR guarantor_last_name IS NOT NULL
    """)
    
    # Удаляем новые колонки
    op.drop_column('guarantor_requests', 'guarantor_last_name')
    op.drop_column('guarantor_requests', 'guarantor_first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    
    # ### end Alembic commands ###
