name: CD - Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 195.93.152.69
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/azv_motors_backend_v2
            git pull origin main
            docker compose down
            docker compose up -d --build
      
      - name: Deploy Test Environment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 195.93.152.69
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/azv_motors_backend_v2
            docker compose -f docker-compose.test.yml down
            docker compose -f docker-compose.test.yml up -d --build
